# Generated by Django 3.1.7 on 2021-03-24 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ApartmentsPics',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ap_number', models.SmallIntegerField(choices=[(1, '1'), (2, '2'), (0, 'other')])),
                ('title', models.CharField(max_length=100)),
                ('placement', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('pic', models.ImageField(upload_to='photos')),
            ],
        ),
    ]
