# Generated by Django 3.1.7 on 2021-03-27 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='apartmentspics',
            name='gallery',
            field=models.BooleanField(default=None),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='apartmentspics',
            name='ap_number',
            field=models.SmallIntegerField(choices=[(1, '1'), (2, '2'), (3, 'mainpage'), (0, 'other')]),
        ),
    ]
