# Generated by Django 3.1.7 on 2021-03-16 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apartmentspics',
            name='ap_number',
            field=models.SmallIntegerField(choices=[(1, '1'), (2, '2')]),
        ),
    ]
